# Server port
server.port=8080

# Google Custom Search API (replace with your values)
spring.application.name=search
google.cse.enabled=true
google.cse.apiKey=
google.cse.cx=225cf0ccf26304fce

# WebTree defaults (optional)
foodsearch.decay=0.6
foodsearch.maxDepth=2
foodsearch.maxNodes=50

#Gemini Flash 2.5 API Key
gemini.api.key=
